---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - calibre
  - plex # Move to nas
  - radarr
  - sabnzbd
  - shared
  - sonarr
  - bazarr


