# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:OGWWfWIzLHDTPkFnb4dlBBQdI5I00s/PrWtM/Bqg37O9xsu9TnlTCeqM1ZG6nsrmHFXENztevplFE0QjEZrpN2aRxZmMUE9wIspl4tBpuh8MrNfAz1eeZqfbqdFn4SZSAMNRqDSEqJXzonBL7eVAdDBw7hYuNylN8K81lh7yxPVZgCFxzFShXYM0GKdIJUTWA53YT1BDaL2vHtNLbRhNibUXVU6c1HX0s5wKKph6LrbnDlQ504pErssOLrc0Eybu6gAZ1s5GwqAES++Bx+oKt+yk2DRs7zI7oifbmmr6jDXA3wvSHuCbSJEkwfFD6kjmD3CzVeyIqA7lLjis4IPY6qFvq1QYkH26BI9OTh8NE75VLEvvgkfLhA7MjZYEKnuVHW1Vs/9pLQGllgT6+FneoE5elu7EevF/6suQ+cVx3w0jM01VsGt8fE2OuoihbP4fKEh4Aw+eX5qr/Bx3UY6gGmJGYwPudKkaX7stXPbjWbo5vXeQ6cMK5UGtZRVmnxvjQ/ciztTQceDKLFRMzcL4ohbhWumY0We07JSv7VdIVcGXDKy9ZbPmRHEj/BU+Jax8K1iv1/qJSoJnVglVAEpW4Ma52yDd5XRrX0RgwXvFYzX7XwIdosx8HlANgTkf137oL+Fb4a2aLgh35UJBj9M2zFzPTxkDscz5WEXz//RA3ewiqg/kZ3j8lclbY1/VGoTL0lgK2wITFpBmlyI937t6Ei7eumdlVzr9AdHpkwIYVEJiat0QfPhxyjWuQjLpD8yP+amBB1plMYg0jq7zncmY+C0UdWAI3pCWgQuySyMyS7AH0u//8lBCLC02DYvlcVIFe0xIpgPyiZAOpgewzMAQmlnM,iv:hpLK0HaqyJBKbkeHfR0hx/9mV929BBQybiwf+ymimgI=,tag:QkhRWjkSlnQcaveCB2FBIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNlE5YlRSM014VytOMm9D
            VFdLVUtHZkRaUkRtbHR0MUErempaZUJFREZVClVGOTdmYStjNGdST1lZN1Y4N0x4
            ZzBpU2NDajVZbU13VnJxbTY1dmRyRmcKLS0tIFk1SnRBZG9laFkrcFhuNGRPTytk
            b0hYU3NRaDU2R1poaDdoRG85QXBPRHMKfK5R6kSfkgMfl8yerX5phiHL5j9f8QDL
            1fZ6xonpscnEc6GHrHIehI1nv6S8BjIZbFNGNprk+mTwm8Ld4Jy+NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-18T16:28:30Z"
    mac: ENC[AES256_GCM,data:LeFLvgWwWg0D33Mm1S2z/LXsyXF2kROcHgahP6llfmNlCIL1hJrB8UkK4IBfH1SM9MY0D++sYftW52fHIXVnXf91SdMd5YR/VzqXDMr1L6IGo2JMlz1URVxId5tS62E5te+YjxOzVDaI+2ZQdWkNzStc03LxpyJNzRKahNRK2BA=,iv:x2w9KKgtlphI3etn0R29hHxfx1Z9xiR/aYW4i/BUAZg=,tag:HfOYWK8+f/CPlNGwC1mnjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
