ansible_become_pass: ENC[AES256_GCM,data:QytwsxIVwYA5aFH4LXrM,iv:2fB7FDyBlvGVa4iRSmWuSCVierLTR/aRd/XbmmoBVD8=,tag:5V7YzC/k1XBmakaKoI01ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10fwvu8qek845zrvegt9tdj22gl68m6fv566swt08kxhpuq08lqlqlh3m7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUm1HQUZWQ01PY296MCs3
            WmRFSkZXU1dqakFiNFlkd05hb2N6US8zNW13CkJJRXRlemwwcndDbVVpMWh4bHov
            NXVRNzJsdDk5dVFuaHY1VjB4QkwzY0UKLS0tIEVYbzdZTmhUeVRYMFp3QWJnV1hl
            UVBHcXE2SzFLWDF1Rm41cDBnRUNycm8KtBYBYH46P5eCK+c7fyZiW0Aso9xP6tpc
            kHBpAejg8OUxVuoQUd7uaZGKaKnaaPa/JukcAuKm6jq+A+p0laDitA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-17T00:12:57Z"
    mac: ENC[AES256_GCM,data:ToIine2asbs1heGBBMOQjdHPlfOUFORjzQ8bFtIRCU0dQQZ40Vg51nlazXKehOKGWxs8+uOoWgsXG9QsRkxjDWJhLAOvo+wsj9Gc7USn/Fz/OCXSMKWpcZgsfXyBM7uyOLv+lW7aIM+s7YZ7spTqWChXqVwTCZq9LTxhPb0zfGA=,iv:q7pLrExjmdsXMyYCAn3jixu8ONLw4pVCB9Y/eJdFJWU=,tag:KVV1iNQiL4h2o1vAwkAY2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
