apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:/FD43X6o,iv:Wh87eAZ/ywWjwN/V8xP+L0yxazNGTtH/ig8x2LhQd6o=,tag:odsnp1haVupvrZbOX+/vBQ==,type:str]
    admin-user: ENC[AES256_GCM,data:Gn5nM/w=,iv:Y1e/osWraW+7IUsIFc/aOBdt2e5jC/tRQ+Gi89xm87w=,tag:87ryX20Ysb6kA+XPG0p2zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10fwvu8qek845zrvegt9tdj22gl68m6fv566swt08kxhpuq08lqlqlh3m7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZjZKMU0vaFJGNWRPbE5P
            VHZwVnoyQXdCRTNVdFQrUGRrcXdGQ05CWDBvClJlaVBPQmtrWS9tMjROcGlBMDZz
            K241d29WZW5yVHdudXRBeGxJWHFIYTAKLS0tIDZPNXVyQ244QnlKMHY3Ulo5dmNt
            bTNuUVF4V0lIK2xUT0xSNWFyem1kUUUKRAFkE31gI6nAgzmbAXn0tp5xCnEwMo3l
            wiYidJg4lp+0izQiTmmG0TosjDkc9I6NgO05k9j/snO8ZKjjLc8viA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T01:35:04Z"
    mac: ENC[AES256_GCM,data:cv/2ngSgIzU/bDlEdxgh6UYeSHAAO5J0wrJX3CsICzQ8F0YpDmWu9l4y3Bit/AW0mSYVv+sppyDey5l1vTmzqyvuQO64z2w9+4qaZKwIXzR7EN/IfJToRyo9z2jhFK0eAoHk/cVg1bUdpcQrDywKHaBApaD9CaMiYHo0wRXAJrA=,iv:XuWBM5GdGDYPr57nAxvRb0Px4WcF+kjCok8FdZTf0tU=,tag:2/Gp/ScqiubfGp4JaCA4QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
