apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:7ZsmijGbMg1RjN0oO3pX,iv:HuPue68iW52K22rrLDCtTao1WW4Uiy1r907qWn3F6Dk=,tag:17i916e3A6dM4MKcJ7fONw==,type:str]
    admin-user: ENC[AES256_GCM,data:/vpMBMFcqjk=,iv:1SZhIsnGwrdMRut4CIT+xlYegZ4jWAbG1Kq5zSibkZg=,tag:adLNWUiIIqyaUGYUDkqMBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10fwvu8qek845zrvegt9tdj22gl68m6fv566swt08kxhpuq08lqlqlh3m7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcjlHK3p3ck95WjdVMU16
            SDlmRmpFeG94MW0vZjAzdStOQVdiVHU1czFBClZqR3YrRjI2NHlaeXZOTVBMOVJZ
            S2tDSUx1dWcwamlQVHJ6WDRCdVU3cU0KLS0tIGxLRUhjWkU1dWcrQlBNcytTbCsr
            d2hGK09WS25la2xremJWZWNoenl1N0UKcjIpB6u848iA+G3eas+1C1X51/JQfkv2
            vSB9kV71c03mmDod3MeN8I+G7oxbCDYMYotm2/FXeVjltX1GZnB/fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T00:26:33Z"
    mac: ENC[AES256_GCM,data:RsU+Vfe/jALdq04TBSruQsrSIfZmC34fOgqJn8kEM/QW4XKuDLJdkQfheiRG2fPmKUTzR7lMxpp7JF+8e8ks76oW4rpQZ1cW3augWq5jzfM37wLfx5EXiTW8IKGB2QFsU6TMx4YmMX3WlpEL65buMB0OOA4/4XHrUZQjmwLPtPw=,iv:0ERGKwbuDKwlkzCCBNX83BnPx6pOWVYik6X9EVpGEvw=,tag:YBzpIcQDxnExcp9BMfbALA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
