apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7jZlIEQ1Vn/SfgHiPueVRv7/xBdpgEM97jJu5Dr88k4zxbNkn9DVVQ==,iv:7K6i6SfTuWo3prsGRbhtnj4OTi/N35VrVN0CSK32n3A=,tag:gvfr7mzkWd3znTOguY0NzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10fwvu8qek845zrvegt9tdj22gl68m6fv566swt08kxhpuq08lqlqlh3m7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRmo3ekJrMzBxd1JWeUFU
            ajQ3YmsxZWs4cW1zeGdyQ1RaeDVpWm9NbWlrCnVWSjFmZitUMzN6aHFtTVcrTko1
            RWFNeHYwZFB0UmtQb0VoclhxRUI0cHcKLS0tIE1JaWE5Q3d5enhEeWp5YjkvS09H
            K0RNaUZZYnZEMXhib0ppWlRPY2Vzd2MKdusaW9m6UTvOvFpPaBsUeBlMj9pSdIkc
            UHERPJeRUXVadhxhKfegf+lxvWzEE2v3lONjEg+wHxEZThghdNAw4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T22:22:33Z"
    mac: ENC[AES256_GCM,data:N/dSK6LiMIap1K6nHuM41eKyb8+fxbgTDFNYzoQGmr/ZWNBHk3TN6t3NYeFEOO8/E616incf1ZS76WepAUWScSxVSC2SsrFxePXNJeaxwFDEuletv0dFh5yUpOaVm6f9OX5QcamyrniVpVl64yc0E74ssqXcQTNBFIjmgmOiUz0=,iv:guMBDaD3cPBQfZAoYNQMKuNF6MLXN/MepQJK3OtBJUI=,tag:xMRdH5vuzuvoHgHGqnzQPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
