---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr
  labels:
    app: bazarr
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/bazarr"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bazarr
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: bazarr
      storage: 1Gi
  selector:
    matchLabels:
      app: bazarr
