---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mastodon-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SECRET_KEY_BASE: |-
          {{ .mastodon_secret_key }}
        password: |-
          {{ .mastodon_pg_password }}
        redis-password: |-
          {{ .mastodon_redis_password }}
  data:
    - secretKey: mastodon_secret_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 89952a6e-e6b4-42fe-bd10-b03101152592
        property: secret_key
    - secretKey: mastodon_pg_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 89952a6e-e6b4-42fe-bd10-b03101152592
        property: pg_password
    - secretKey: mastodon_redis_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 89952a6e-e6b4-42fe-bd10-b03101152592
        property: redis_password
