apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:k0ytEJS87aqjpkZPaG8IoP+/Xu2tCa7oqeZIqSxBTneSPCjkTvqsOw==,iv:79WQnBDaPc9fvuCk+CqM4o5VrMlXqAocp36UzJjCOcA=,tag:m05xKzP602B2mHiNnzeg4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10fwvu8qek845zrvegt9tdj22gl68m6fv566swt08kxhpuq08lqlqlh3m7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN2JTK2VCNFNxNkhzSjZs
            U3ZXV0podHVOZlBnVmFNZHE5WkRGWUR5SkZZCmpnQzNFRTE1TU1BditsWEEzcndT
            VmdOeTZ4MGZMNmszOFBXSVlYWm5scjgKLS0tIFMzckRqSFFxQnNGZzlKWGlSdkRo
            bnVqZXBIbTdzMHIzY3g1QnphV2VFa2cKQLz3JlZE6cHhV2aiNTVrL7qtTNQ5R7B0
            nsDmm02gwryBAwbWsM+G/t5kaDlFR0CqX+MpsXJmVx9GOHRvrzAnzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T22:22:33Z"
    mac: ENC[AES256_GCM,data:BWTn2E/7KONFkd+tolX174kFBN6fW7CttyPGQPPPTjlqVb6/3LIOUOqi02TXxeU4RW47dClnnOE4A9B1+GcVEhMczC2kBw6TNxqfPF0zcWpHQezaQBq/rnDlod68XX2kDidkDAz5rMpm6PEtrtGU99vJ2QgJViRJ0N/rDeBpgyw=,iv:vkKhH6wpXMyzpYweYAbnZnQuqVidICtMgmXBtM9C73Y=,tag:aspTnShCakTCvX4+gSf6zw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
