---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app redis
  namespace: mastodon
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 20.13.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    master:
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
    auth:
      enabled: false
      sentinel: false
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
      resources:
        requests:
          cpu: 10m
          memory: 10M
        limits:
          memory: 20M

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
