---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app calibre
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: version-v6.27.0
    env:
      PGID: "1000"
      PUID: "1000"

    podSecurityContext:
      # runAsUser: 1000
      # runAsGroup: 1000
      supplementalGroups:
        - 100
        # - 568

    initContainers:
      update-config-ownership:
        image: busybox:1.36.1
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 0
      update-config-permission:
        image: busybox:1.36.1
        command: ["sh", "-c", "chmod -R 774 /config"]
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 0

    # Pod
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "250m"

    # Persistence
    persistence:
      # Make sure it has pid/gid 568
      # and it is pre-populated
      config:
        enabled: true
        existingClaim: calibre
      books:
        enabled: true
        existingClaim: book
        mountPath: /books

    # Linuxserver's calibre has their port at 8083
    service:
      main:
        ports:
          http:
            port: 8083

    # Network
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "book"
          coredns.io/hostname: &host "calibre.${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - *host
        tls:
          - hosts:
              - *host
