---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre
  labels:
    app: calibre
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: calibre
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: calibre
