apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:juhUw87vrO3hmUFH2dltSBc=,iv:2b661LxnyL+t830s9WSkibEWtQp3glCflDxFEyrsqtQ=,tag:zDqzsGwHiWTi3UUZYW2pPA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:nzbWrFTxpRjLp8hMxJxXu4MGM7DhG+JWihQPbazaS/vRGMqW,iv:jDAwkc4E7EmNjT06ZhuivPGh6A4A0x3xfNIP/XiiyRc=,tag:2VNyGgTrfejE80UTkLmZEg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:QMj9InIR4xsL,iv:iwSKLElnBWDxKno4aAM+070wo9MKkRRlE/SbFEUK4cs=,tag:QnSP6tcSwwd61VwtUp+7aA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10fwvu8qek845zrvegt9tdj22gl68m6fv566swt08kxhpuq08lqlqlh3m7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdmsyVEorcWRCbGxRSW5P
            bEV4ZUtTMFp6N2NvaFVERkhNN1N5R09PY1RzClRNQWpwUGV2a2Z5dzh6V2xkeDhw
            VkNTemw2U3pVbnA1a2JncndVeUtJb1kKLS0tIGZQa3AwamNDUktzUnd4bVFET3J2
            ZFI0QlY1UlFmWVVIdlNrKzdEMC9IK1UKeY+kebIv+SyzZj1p6F9+ouTDQzVGclN7
            7LU+gxda+GeGzCudXBlvXNXhiHn5Yg4aQV6+MYpXNYXhnh4uTRUB+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-17T00:13:21Z"
    mac: ENC[AES256_GCM,data:gyClBvQT7vbvpH7EyVNEoTnmR+V9e2PvIRFPUcaKDNRsLaiDQBYDdZFngkPhd62txfANcNw67dAhJv3Wlo73RIcnXL6KYboT6yhFvagXQx0Qge7rJGxfBBaImWWOPy9TvLMa5obB8KHD86F9bj54KZi7YOhKoVddjG0FU9jEzVM=,iv:kpfqpfFUdZFpElrO37/rZzanZfClHrmADIo02FLaSSk=,tag:fYWGMOW6RES/iZK07u42Kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
