---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/sonarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: sonarr
