apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:PZEFRLY47g8WDOQX31IXT815JL8qSel3H4D99AZANfM084pH,iv:MMQOTFEjBvQKi9XYH0VfL1ihqFVAIh/gExOlvrTC75o=,tag:UCC5RM5tPhXLSVM2xbYlLw==,type:str]
    credentials.json: ENC[AES256_GCM,data:bznp1a++d8x3FZUs76LPHtIv4kdllPuhjtv7GpR5ckfW/HdPS87PxF53OMXpN/5DcP569ffs9O2hl+K6cou41XqIWiy+ZZsI9BdLw4pdgEkOG78dU2jnmV1gAmDgEDwvrSRQQ3BStYLm1RYuwBbc3TOAWEvJ/R0PcG0BXZol9CzZOovVPfB0QovvopbN5W9JvYDBr5kqTG2qJX7Pfg7EQEVxI5yvdN45FIPNRtGg2w==,iv:NzeXyfmOP6l/in2c774LXbXxW06lD4RwIUBWeEEPZbY=,tag:MZP+5WOhldPBD4CfJAr3qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10fwvu8qek845zrvegt9tdj22gl68m6fv566swt08kxhpuq08lqlqlh3m7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS0tJaHJjejgrbm5ZR1Zl
            RXc5cjNYQ09NV0hkQkx0Q3FrWFVseStlc0RBCjVpZmlRWUMzOWYxMzV4bytXbHZs
            WTZvSmlRZlBhVUpVWWlpMkVLYVJ0YUEKLS0tIHlxMitSb0hydGN4d3VZRS9qSFBV
            NHlmcVNKY0pSd3ZReXJGQk9kUURiK0UKhcxw4J5K2GlTeLaPp5C4WPKWPJ09BKKA
            jH0kUAgOzBtO1rm8FeMrzn82cuN9miyriEUme96SfVMIvNE9VubXLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T01:35:02Z"
    mac: ENC[AES256_GCM,data:5sm8s3bvU4EA0CwkCAdjniZqVNNVXixSFKTLDhSNVRVYyzUHpC6jMat1etndfT3Jt5K/93N0WUQOTRNu6u0ShKZrUc2K/pjhyyoxTeYdXDTUaRmB+r6mxPh5i+AFXrK5PAyqrLEUm53RLBv3qN7De6nfhEcOUZscrRN303Py9RI=,iv:XYJnerP94MXOIB7v0hveh0viZJ6rkUmGf5/C5rjR5uQ=,tag:yvn8cSBW/su+qRjr+So8dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
