---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: mastodon
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: 13.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      postgresql:
        auth:
          postgresPassword: "${POSTGRES_ADMIN_PASSWORD}"
          username: mastodon
          password: "${POSTGRES_PASSWORD}"
          database: mastodon
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "16.0.0"
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql-data
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
