---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex
  labels:
    app: plex
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/plex"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: plex
      storage: 1Gi
  selector:
    matchLabels:
      app: plex
